var annotated_dup =
[
    [ "hdf5", "namespacehdf5.html", [
      [ "dataspace", "namespacehdf5_1_1dataspace.html", [
        [ "TypeTrait< pni::array >", "classhdf5_1_1dataspace_1_1TypeTrait_3_01pni_1_1array_01_4.html", "classhdf5_1_1dataspace_1_1TypeTrait_3_01pni_1_1array_01_4" ],
        [ "TypeTrait< pni::mdarray< StorageT, IndexMapT, InplaceArithmeticT > >", "classhdf5_1_1dataspace_1_1TypeTrait_3_01pni_1_1mdarray_3_01StorageT_00_01IndexMapT_00_01InplaceArithmeticT_01_4_01_4.html", "classhdf5_1_1dataspace_1_1TypeTrait_3_01pni_1_1mdarray_3_01StorageT_00_01IndexMapT_00_01InplaceArithmeticT_01_4_01_4" ]
      ] ],
      [ "datatype", "namespacehdf5_1_1datatype.html", [
        [ "TypeTrait< pni::array >", "classhdf5_1_1datatype_1_1TypeTrait_3_01pni_1_1array_01_4.html", "classhdf5_1_1datatype_1_1TypeTrait_3_01pni_1_1array_01_4" ],
        [ "TypeTrait< pni::mdarray< StorageT, IndexMapT, InplaceArithmeticT > >", "classhdf5_1_1datatype_1_1TypeTrait_3_01pni_1_1mdarray_3_01StorageT_00_01IndexMapT_00_01InplaceArithmeticT_01_4_01_4.html", "classhdf5_1_1datatype_1_1TypeTrait_3_01pni_1_1mdarray_3_01StorageT_00_01IndexMapT_00_01InplaceArithmeticT_01_4_01_4" ]
      ] ],
      [ "VarLengthStringTrait< pni::dynamic_array< std::string > >", "classhdf5_1_1VarLengthStringTrait_3_01pni_1_1dynamic__array_3_01std_1_1string_01_4_01_4.html", "classhdf5_1_1VarLengthStringTrait_3_01pni_1_1dynamic__array_3_01std_1_1string_01_4_01_4" ]
    ] ],
    [ "pni", "namespacepni.html", [
      [ "cbf", "namespacepni_1_1cbf.html", [
        [ "dectris_reader", "classpni_1_1cbf_1_1dectris__reader.html", "classpni_1_1cbf_1_1dectris__reader" ]
      ] ],
      [ "nexus", "namespacepni_1_1nexus.html", [
        [ "xml", "namespacepni_1_1nexus_1_1xml.html", [
          [ "AttributeBuilder", "classpni_1_1nexus_1_1xml_1_1AttributeBuilder.html", "classpni_1_1nexus_1_1xml_1_1AttributeBuilder" ],
          [ "BuilderFactory", "classpni_1_1nexus_1_1xml_1_1BuilderFactory.html", "classpni_1_1nexus_1_1xml_1_1BuilderFactory" ],
          [ "DatasetCreationListBuilder", "classpni_1_1nexus_1_1xml_1_1DatasetCreationListBuilder.html", "classpni_1_1nexus_1_1xml_1_1DatasetCreationListBuilder" ],
          [ "DataspaceBuilder", "classpni_1_1nexus_1_1xml_1_1DataspaceBuilder.html", "classpni_1_1nexus_1_1xml_1_1DataspaceBuilder" ],
          [ "DatatypeBuilder", "classpni_1_1nexus_1_1xml_1_1DatatypeBuilder.html", "classpni_1_1nexus_1_1xml_1_1DatatypeBuilder" ],
          [ "DataWriter", "classpni_1_1nexus_1_1xml_1_1DataWriter.html", "classpni_1_1nexus_1_1xml_1_1DataWriter" ],
          [ "DimensionNodeHandler", "classpni_1_1nexus_1_1xml_1_1DimensionNodeHandler.html", "classpni_1_1nexus_1_1xml_1_1DimensionNodeHandler" ],
          [ "FieldBuilder", "classpni_1_1nexus_1_1xml_1_1FieldBuilder.html", "classpni_1_1nexus_1_1xml_1_1FieldBuilder" ],
          [ "GroupBuilder", "classpni_1_1nexus_1_1xml_1_1GroupBuilder.html", "classpni_1_1nexus_1_1xml_1_1GroupBuilder" ],
          [ "LinkBuilder", "classpni_1_1nexus_1_1xml_1_1LinkBuilder.html", "classpni_1_1nexus_1_1xml_1_1LinkBuilder" ],
          [ "Node", "classpni_1_1nexus_1_1xml_1_1Node.html", "classpni_1_1nexus_1_1xml_1_1Node" ],
          [ "ObjectBuilder", "classpni_1_1nexus_1_1xml_1_1ObjectBuilder.html", "classpni_1_1nexus_1_1xml_1_1ObjectBuilder" ]
        ] ],
        [ "AttributeList", "classpni_1_1nexus_1_1AttributeList.html", null ],
        [ "BaseClassFactory", "classpni_1_1nexus_1_1BaseClassFactory.html", "classpni_1_1nexus_1_1BaseClassFactory" ],
        [ "DatasetList", "classpni_1_1nexus_1_1DatasetList.html", "classpni_1_1nexus_1_1DatasetList" ],
        [ "DatatypeFactory", "classpni_1_1nexus_1_1DatatypeFactory.html", "classpni_1_1nexus_1_1DatatypeFactory" ],
        [ "DateTime", "classpni_1_1nexus_1_1DateTime.html", "classpni_1_1nexus_1_1DateTime" ],
        [ "FieldFactory", "classpni_1_1nexus_1_1FieldFactory.html", "classpni_1_1nexus_1_1FieldFactory" ],
        [ "GroupList", "classpni_1_1nexus_1_1GroupList.html", "classpni_1_1nexus_1_1GroupList" ],
        [ "IsBaseClass", "classpni_1_1nexus_1_1IsBaseClass.html", "classpni_1_1nexus_1_1IsBaseClass" ],
        [ "IsData", "classpni_1_1nexus_1_1IsData.html", "classpni_1_1nexus_1_1IsData" ],
        [ "IsDetector", "classpni_1_1nexus_1_1IsDetector.html", "classpni_1_1nexus_1_1IsDetector" ],
        [ "IsEntry", "classpni_1_1nexus_1_1IsEntry.html", "classpni_1_1nexus_1_1IsEntry" ],
        [ "IsInstrument", "classpni_1_1nexus_1_1IsInstrument.html", "classpni_1_1nexus_1_1IsInstrument" ],
        [ "IsSample", "classpni_1_1nexus_1_1IsSample.html", "classpni_1_1nexus_1_1IsSample" ],
        [ "IsSubentry", "classpni_1_1nexus_1_1IsSubentry.html", "classpni_1_1nexus_1_1IsSubentry" ],
        [ "IsTransformation", "classpni_1_1nexus_1_1IsTransformation.html", "classpni_1_1nexus_1_1IsTransformation" ],
        [ "IsValidNeXusName", "classpni_1_1nexus_1_1IsValidNeXusName.html", "classpni_1_1nexus_1_1IsValidNeXusName" ],
        [ "NodeList", "classpni_1_1nexus_1_1NodeList.html", null ],
        [ "NodePredicate", "classpni_1_1nexus_1_1NodePredicate.html", "classpni_1_1nexus_1_1NodePredicate" ],
        [ "ObjectBuilder", "classpni_1_1nexus_1_1ObjectBuilder.html", "classpni_1_1nexus_1_1ObjectBuilder" ],
        [ "Path", "classpni_1_1nexus_1_1Path.html", "classpni_1_1nexus_1_1Path" ],
        [ "PathObject", "classpni_1_1nexus_1_1PathObject.html", "classpni_1_1nexus_1_1PathObject" ],
        [ "PathObjectList", "classpni_1_1nexus_1_1PathObjectList.html", "classpni_1_1nexus_1_1PathObjectList" ],
        [ "Version", "classpni_1_1nexus_1_1Version.html", "classpni_1_1nexus_1_1Version" ]
      ] ],
      [ "nx", "namespacepni_1_1nx.html", [
        [ "xml", "namespacepni_1_1nx_1_1xml.html", [
          [ "link", "classpni_1_1nx_1_1xml_1_1link.html", "classpni_1_1nx_1_1xml_1_1link" ]
        ] ]
      ] ],
      [ "tiff", "namespacepni_1_1tiff.html", [
        [ "ifd", "classpni_1_1tiff_1_1ifd.html", "classpni_1_1tiff_1_1ifd" ],
        [ "ifd_entry", "classpni_1_1tiff_1_1ifd__entry.html", "classpni_1_1tiff_1_1ifd__entry" ],
        [ "ifd_entry_reader", "classpni_1_1tiff_1_1ifd__entry__reader.html", "classpni_1_1tiff_1_1ifd__entry__reader" ],
        [ "ifd_entry_reader< pni::string, pni::string >", "classpni_1_1tiff_1_1ifd__entry__reader_3_01pni_1_1string_00_01pni_1_1string_01_4.html", "classpni_1_1tiff_1_1ifd__entry__reader_3_01pni_1_1string_00_01pni_1_1string_01_4" ],
        [ "rational", "classpni_1_1tiff_1_1rational.html", "classpni_1_1tiff_1_1rational" ],
        [ "strip_reader", "classpni_1_1tiff_1_1strip__reader.html", "classpni_1_1tiff_1_1strip__reader" ],
        [ "tiff_read_error", "classpni_1_1tiff_1_1tiff__read__error.html", "classpni_1_1tiff_1_1tiff__read__error" ]
      ] ],
      [ "add_op", "classpni_1_1add__op.html", "classpni_1_1add__op" ],
      [ "and_t", "structpni_1_1and__t.html", "structpni_1_1and__t" ],
      [ "array", "classpni_1_1array.html", "classpni_1_1array" ],
      [ "array_factory", "structpni_1_1array__factory.html", "structpni_1_1array__factory" ],
      [ "array_holder", "classpni_1_1array__holder.html", "classpni_1_1array__holder" ],
      [ "array_holder_interface", "classpni_1_1array__holder__interface.html", "classpni_1_1array__holder__interface" ],
      [ "array_iterator", "classpni_1_1array__iterator.html", "classpni_1_1array__iterator" ],
      [ "array_iterator_types", "structpni_1_1array__iterator__types.html", null ],
      [ "array_iterator_types< 0 >", "structpni_1_1array__iterator__types_3_010_01_4.html", "structpni_1_1array__iterator__types_3_010_01_4" ],
      [ "array_iterator_types< 1 >", "structpni_1_1array__iterator__types_3_011_01_4.html", "structpni_1_1array__iterator__types_3_011_01_4" ],
      [ "array_selection", "classpni_1_1array__selection.html", "classpni_1_1array__selection" ],
      [ "array_trait", "structpni_1_1array__trait.html", "structpni_1_1array__trait" ],
      [ "array_trait< Operand1T, scalar< ScalarOperandT > >", "structpni_1_1array__trait_3_01Operand1T_00_01scalar_3_01ScalarOperandT_01_4_01_4.html", "structpni_1_1array__trait_3_01Operand1T_00_01scalar_3_01ScalarOperandT_01_4_01_4" ],
      [ "array_trait< scalar< ScalarOperandT >, Operand1T >", "structpni_1_1array__trait_3_01scalar_3_01ScalarOperandT_01_4_00_01Operand1T_01_4.html", "structpni_1_1array__trait_3_01scalar_3_01ScalarOperandT_01_4_00_01Operand1T_01_4" ],
      [ "array_view", "classpni_1_1array__view.html", "classpni_1_1array__view" ],
      [ "array_view_trait", "structpni_1_1array__view__trait.html", null ],
      [ "array_view_trait< ArrayT, false >", "structpni_1_1array__view__trait_3_01ArrayT_00_01false_01_4.html", "structpni_1_1array__view__trait_3_01ArrayT_00_01false_01_4" ],
      [ "array_view_trait< ArrayT, true >", "structpni_1_1array__view__trait_3_01ArrayT_00_01true_01_4.html", "structpni_1_1array__view__trait_3_01ArrayT_00_01true_01_4" ],
      [ "binary_t", "classpni_1_1binary__t.html", "classpni_1_1binary__t" ],
      [ "bool_t", "classpni_1_1bool__t.html", "classpni_1_1bool__t" ],
      [ "c_index_map_imp", "classpni_1_1c__index__map__imp.html", "classpni_1_1c__index__map__imp" ],
      [ "cbf_reader", "classpni_1_1cbf__reader.html", "classpni_1_1cbf__reader" ],
      [ "checked_convertible", "structpni_1_1checked__convertible.html", "structpni_1_1checked__convertible" ],
      [ "cli_argument_error", "classpni_1_1cli__argument__error.html", "classpni_1_1cli__argument__error" ],
      [ "cli_error", "classpni_1_1cli__error.html", "classpni_1_1cli__error" ],
      [ "cli_help_request", "classpni_1_1cli__help__request.html", "classpni_1_1cli__help__request" ],
      [ "cli_option_error", "classpni_1_1cli__option__error.html", "classpni_1_1cli__option__error" ],
      [ "column_info", "classpni_1_1column__info.html", "classpni_1_1column__info" ],
      [ "container_io_config", "classpni_1_1container__io__config.html", "classpni_1_1container__io__config" ],
      [ "container_iterator", "classpni_1_1container__iterator.html", "classpni_1_1container__iterator" ],
      [ "container_trait", "structpni_1_1container__trait.html", "structpni_1_1container__trait" ],
      [ "container_trait< array_view< ArrayT > >", "structpni_1_1container__trait_3_01array__view_3_01ArrayT_01_4_01_4.html", "structpni_1_1container__trait_3_01array__view_3_01ArrayT_01_4_01_4" ],
      [ "container_trait< mdarray< StorageT, IndexMapT, InplaceArithmeticT > >", "structpni_1_1container__trait_3_01mdarray_3_01StorageT_00_01IndexMapT_00_01InplaceArithmeticT_01_4_01_4.html", "structpni_1_1container__trait_3_01mdarray_3_01StorageT_00_01IndexMapT_00_01InplaceArithmeticT_01_4_01_4" ],
      [ "container_trait< std::array< DataT, TDimN > >", "structpni_1_1container__trait_3_01std_1_1array_3_01DataT_00_01TDimN_01_4_01_4.html", "structpni_1_1container__trait_3_01std_1_1array_3_01DataT_00_01TDimN_01_4_01_4" ],
      [ "container_trait< std::list< ArrayArgsT... > >", "structpni_1_1container__trait_3_01std_1_1list_3_01ArrayArgsT_8_8_8_01_4_01_4.html", "structpni_1_1container__trait_3_01std_1_1list_3_01ArrayArgsT_8_8_8_01_4_01_4" ],
      [ "container_trait< std::vector< ArrayArgsT... > >", "structpni_1_1container__trait_3_01std_1_1vector_3_01ArrayArgsT_8_8_8_01_4_01_4.html", "structpni_1_1container__trait_3_01std_1_1vector_3_01ArrayArgsT_8_8_8_01_4_01_4" ],
      [ "container_utils", "structpni_1_1container__utils.html", "structpni_1_1container__utils" ],
      [ "container_utils< std::array< ElementT, TDimN > >", "structpni_1_1container__utils_3_01std_1_1array_3_01ElementT_00_01TDimN_01_4_01_4.html", "structpni_1_1container__utils_3_01std_1_1array_3_01ElementT_00_01TDimN_01_4_01_4" ],
      [ "conversion_strategy", "structpni_1_1conversion__strategy.html", "structpni_1_1conversion__strategy" ],
      [ "conversion_strategy< hdf5::datatype::EBool, bool_t, true >", "structpni_1_1conversion__strategy_3_01hdf5_1_1datatype_1_1EBool_00_01bool__t_00_01true_01_4.html", "structpni_1_1conversion__strategy_3_01hdf5_1_1datatype_1_1EBool_00_01bool__t_00_01true_01_4" ],
      [ "conversion_strategy< TargetT, SourceT, false >", "structpni_1_1conversion__strategy_3_01TargetT_00_01SourceT_00_01false_01_4.html", "structpni_1_1conversion__strategy_3_01TargetT_00_01SourceT_00_01false_01_4" ],
      [ "conversion_trait", "structpni_1_1conversion__trait.html", "structpni_1_1conversion__trait" ],
      [ "conversion_trait< pni::int8 >", "structpni_1_1conversion__trait_3_01pni_1_1int8_01_4.html", "structpni_1_1conversion__trait_3_01pni_1_1int8_01_4" ],
      [ "conversion_trait< pni::uint8 >", "structpni_1_1conversion__trait_3_01pni_1_1uint8_01_4.html", "structpni_1_1conversion__trait_3_01pni_1_1uint8_01_4" ],
      [ "converter", "structpni_1_1converter.html", "structpni_1_1converter" ],
      [ "converter< std::complex< BaseT >, SourceT >", "structpni_1_1converter_3_01std_1_1complex_3_01BaseT_01_4_00_01SourceT_01_4.html", "structpni_1_1converter_3_01std_1_1complex_3_01BaseT_01_4_00_01SourceT_01_4" ],
      [ "converter< std::complex< TargetBaseT >, std::complex< SourceBaseT > >", "structpni_1_1converter_3_01std_1_1complex_3_01TargetBaseT_01_4_00_01std_1_1complex_3_01SourceBaseT_01_4_01_4.html", "structpni_1_1converter_3_01std_1_1complex_3_01TargetBaseT_01_4_00_01std_1_1complex_3_01SourceBaseT_01_4_01_4" ],
      [ "converter< TargetT, TargetT >", "structpni_1_1converter_3_01TargetT_00_01TargetT_01_4.html", "structpni_1_1converter_3_01TargetT_00_01TargetT_01_4" ],
      [ "convertible", "structpni_1_1convertible.html", "structpni_1_1convertible" ],
      [ "data_reader", "classpni_1_1data__reader.html", "classpni_1_1data__reader" ],
      [ "div_op", "classpni_1_1div__op.html", "classpni_1_1div__op" ],
      [ "exception", "classpni_1_1exception.html", "classpni_1_1exception" ],
      [ "exception_record", "classpni_1_1exception__record.html", "classpni_1_1exception__record" ],
      [ "file_error", "classpni_1_1file__error.html", "classpni_1_1file__error" ],
      [ "filter_not_available", "classpni_1_1filter__not__available.html", "classpni_1_1filter__not__available" ],
      [ "fio_reader", "classpni_1_1fio__reader.html", "classpni_1_1fio__reader" ],
      [ "format_config", "classpni_1_1format__config.html", "classpni_1_1format__config" ],
      [ "format_str", "structpni_1_1format__str.html", null ],
      [ "get_reference_type", "structpni_1_1get__reference__type.html", "structpni_1_1get__reference__type" ],
      [ "get_reference_type< std::reference_wrapper< GeneralT > >", "structpni_1_1get__reference__type_3_01std_1_1reference__wrapper_3_01GeneralT_01_4_01_4.html", "structpni_1_1get__reference__type_3_01std_1_1reference__wrapper_3_01GeneralT_01_4_01_4" ],
      [ "id_type_map", "structpni_1_1id__type__map.html", "structpni_1_1id__type__map" ],
      [ "image_channel_info", "classpni_1_1image__channel__info.html", "classpni_1_1image__channel__info" ],
      [ "image_info", "classpni_1_1image__info.html", "classpni_1_1image__info" ],
      [ "image_reader", "classpni_1_1image__reader.html", "classpni_1_1image__reader" ],
      [ "index_error", "classpni_1_1index__error.html", "classpni_1_1index__error" ],
      [ "index_iterator", "classpni_1_1index__iterator.html", "classpni_1_1index__iterator" ],
      [ "index_map", "classpni_1_1index__map.html", "classpni_1_1index__map" ],
      [ "inplace_arithmetics", "structpni_1_1inplace__arithmetics.html", "structpni_1_1inplace__arithmetics" ],
      [ "invalid_object_error", "classpni_1_1invalid__object__error.html", "classpni_1_1invalid__object__error" ],
      [ "io_error", "classpni_1_1io__error.html", "classpni_1_1io__error" ],
      [ "is_array", "structpni_1_1is__array.html", "structpni_1_1is__array" ],
      [ "is_complex_type", "structpni_1_1is__complex__type.html", "structpni_1_1is__complex__type" ],
      [ "is_float_type", "structpni_1_1is__float__type.html", "structpni_1_1is__float__type" ],
      [ "is_index_type", "structpni_1_1is__index__type.html", "structpni_1_1is__index__type" ],
      [ "is_index_types", "structpni_1_1is__index__types.html", "structpni_1_1is__index__types" ],
      [ "is_integer_type", "structpni_1_1is__integer__type.html", "structpni_1_1is__integer__type" ],
      [ "is_non_numeric_type", "structpni_1_1is__non__numeric__type.html", "structpni_1_1is__non__numeric__type" ],
      [ "is_numeric_type", "structpni_1_1is__numeric__type.html", "structpni_1_1is__numeric__type" ],
      [ "is_primitive_type", "structpni_1_1is__primitive__type.html", "structpni_1_1is__primitive__type" ],
      [ "is_reference_holder", "structpni_1_1is__reference__holder.html", "structpni_1_1is__reference__holder" ],
      [ "is_reference_holder< std::reference_wrapper< GeneralT > >", "structpni_1_1is__reference__holder_3_01std_1_1reference__wrapper_3_01GeneralT_01_4_01_4.html", "structpni_1_1is__reference__holder_3_01std_1_1reference__wrapper_3_01GeneralT_01_4_01_4" ],
      [ "is_valid_index", "structpni_1_1is__valid__index.html", "structpni_1_1is__valid__index" ],
      [ "is_view_cont", "structpni_1_1is__view__cont.html", "structpni_1_1is__view__cont" ],
      [ "is_view_cont< std::array< ElementT, TDimN > >", "structpni_1_1is__view__cont_3_01std_1_1array_3_01ElementT_00_01TDimN_01_4_01_4.html", "structpni_1_1is__view__cont_3_01std_1_1array_3_01ElementT_00_01TDimN_01_4_01_4" ],
      [ "is_view_cont< std::vector< ElementT > >", "structpni_1_1is__view__cont_3_01std_1_1vector_3_01ElementT_01_4_01_4.html", "structpni_1_1is__view__cont_3_01std_1_1vector_3_01ElementT_01_4_01_4" ],
      [ "is_view_index", "structpni_1_1is__view__index.html", "structpni_1_1is__view__index" ],
      [ "iterator_error", "classpni_1_1iterator__error.html", "classpni_1_1iterator__error" ],
      [ "key_error", "classpni_1_1key__error.html", "classpni_1_1key__error" ],
      [ "link_error", "classpni_1_1link__error.html", "classpni_1_1link__error" ],
      [ "map_utils", "structpni_1_1map__utils.html", "structpni_1_1map__utils" ],
      [ "map_utils< static_index_map< PolicyT, TDimsN... > >", "structpni_1_1map__utils_3_01static__index__map_3_01PolicyT_00_01TDimsN_8_8_8_01_4_01_4.html", "structpni_1_1map__utils_3_01static__index__map_3_01PolicyT_00_01TDimsN_8_8_8_01_4_01_4" ],
      [ "mdarray", "classpni_1_1mdarray.html", "classpni_1_1mdarray" ],
      [ "memory_allocation_error", "classpni_1_1memory__allocation__error.html", "classpni_1_1memory__allocation__error" ],
      [ "memory_not_allocated_error", "classpni_1_1memory__not__allocated__error.html", "classpni_1_1memory__not__allocated__error" ],
      [ "min_max", "structpni_1_1min__max.html", "structpni_1_1min__max" ],
      [ "min_max< FloatT, true >", "structpni_1_1min__max_3_01FloatT_00_01true_01_4.html", "structpni_1_1min__max_3_01FloatT_00_01true_01_4" ],
      [ "mult_op", "classpni_1_1mult__op.html", "classpni_1_1mult__op" ],
      [ "none", "structpni_1_1none.html", null ],
      [ "not_implemented_error", "classpni_1_1not__implemented__error.html", "classpni_1_1not__implemented__error" ],
      [ "not_t", "structpni_1_1not__t.html", "structpni_1_1not__t" ],
      [ "object_error", "classpni_1_1object__error.html", "classpni_1_1object__error" ],
      [ "op_trait", "structpni_1_1op__trait.html", "structpni_1_1op__trait" ],
      [ "op_trait< scalar< GeneralT > >", "structpni_1_1op__trait_3_01scalar_3_01GeneralT_01_4_01_4.html", "structpni_1_1op__trait_3_01scalar_3_01GeneralT_01_4_01_4" ],
      [ "or_t", "structpni_1_1or__t.html", "structpni_1_1or__t" ],
      [ "parser", "classpni_1_1parser.html", "classpni_1_1parser" ],
      [ "parser< hdf5::datatype::EBool >", "classpni_1_1parser_3_01hdf5_1_1datatype_1_1EBool_01_4.html", "classpni_1_1parser_3_01hdf5_1_1datatype_1_1EBool_01_4" ],
      [ "parser< pni::bool_t >", "classpni_1_1parser_3_01pni_1_1bool__t_01_4.html", "classpni_1_1parser_3_01pni_1_1bool__t_01_4" ],
      [ "parser< pni::slice >", "classpni_1_1parser_3_01pni_1_1slice_01_4.html", "classpni_1_1parser_3_01pni_1_1slice_01_4" ],
      [ "parser< pni::string >", "classpni_1_1parser_3_01pni_1_1string_01_4.html", "classpni_1_1parser_3_01pni_1_1string_01_4" ],
      [ "parser< pni::value >", "classpni_1_1parser_3_01pni_1_1value_01_4.html", "classpni_1_1parser_3_01pni_1_1value_01_4" ],
      [ "parser< std::complex< BaseT > >", "classpni_1_1parser_3_01std_1_1complex_3_01BaseT_01_4_01_4.html", "classpni_1_1parser_3_01std_1_1complex_3_01BaseT_01_4_01_4" ],
      [ "parser< std::vector< ElementT > >", "classpni_1_1parser_3_01std_1_1vector_3_01ElementT_01_4_01_4.html", "classpni_1_1parser_3_01std_1_1vector_3_01ElementT_01_4_01_4" ],
      [ "parser_error", "classpni_1_1parser__error.html", "classpni_1_1parser__error" ],
      [ "range_error", "classpni_1_1range__error.html", "classpni_1_1range__error" ],
      [ "scalar", "classpni_1_1scalar.html", "classpni_1_1scalar" ],
      [ "scalar_iterator", "classpni_1_1scalar__iterator.html", "classpni_1_1scalar__iterator" ],
      [ "shape_mismatch_error", "classpni_1_1shape__mismatch__error.html", "classpni_1_1shape__mismatch__error" ],
      [ "size_mismatch_error", "classpni_1_1size__mismatch__error.html", "classpni_1_1size__mismatch__error" ],
      [ "slice", "classpni_1_1slice.html", "classpni_1_1slice" ],
      [ "spreadsheet_reader", "classpni_1_1spreadsheet__reader.html", "classpni_1_1spreadsheet__reader" ],
      [ "static_index_map", "classpni_1_1static__index__map.html", "classpni_1_1static__index__map" ],
      [ "sub_op", "classpni_1_1sub__op.html", "classpni_1_1sub__op" ],
      [ "tiff_reader", "classpni_1_1tiff__reader.html", "classpni_1_1tiff__reader" ],
      [ "type_class_map", "structpni_1_1type__class__map.html", "structpni_1_1type__class__map" ],
      [ "type_error", "classpni_1_1type__error.html", "classpni_1_1type__error" ],
      [ "type_id_container_builder", "classpni_1_1type__id__container__builder.html", "classpni_1_1type__id__container__builder" ],
      [ "type_id_map", "structpni_1_1type__id__map.html", "structpni_1_1type__id__map" ],
      [ "type_info", "structpni_1_1type__info.html", "structpni_1_1type__info" ],
      [ "unchecked_convertible", "structpni_1_1unchecked__convertible.html", "structpni_1_1unchecked__convertible" ],
      [ "value", "classpni_1_1value.html", "classpni_1_1value" ],
      [ "value_converter", "structpni_1_1value__converter.html", "structpni_1_1value__converter" ],
      [ "value_converter< TargetT, SourceT, true >", "structpni_1_1value__converter_3_01TargetT_00_01SourceT_00_01true_01_4.html", "structpni_1_1value__converter_3_01TargetT_00_01SourceT_00_01true_01_4" ],
      [ "value_error", "classpni_1_1value__error.html", "classpni_1_1value__error" ],
      [ "value_holder", "classpni_1_1value__holder.html", "classpni_1_1value__holder" ],
      [ "value_holder_interface", "classpni_1_1value__holder__interface.html", "classpni_1_1value__holder__interface" ],
      [ "value_ref", "classpni_1_1value__ref.html", "classpni_1_1value__ref" ],
      [ "view_provider", "structpni_1_1view__provider.html", null ],
      [ "view_provider< ArrayT, false >", "structpni_1_1view__provider_3_01ArrayT_00_01false_01_4.html", "structpni_1_1view__provider_3_01ArrayT_00_01false_01_4" ],
      [ "view_provider< ArrayT, true >", "structpni_1_1view__provider_3_01ArrayT_00_01true_01_4.html", "structpni_1_1view__provider_3_01ArrayT_00_01true_01_4" ]
    ] ]
];