var error_2exceptions_8hpp =
[
    [ "pni::exception_record", "classpni_1_1exception__record.html", "classpni_1_1exception__record" ],
    [ "pni::exception", "classpni_1_1exception.html", "classpni_1_1exception" ],
    [ "pni::memory_allocation_error", "classpni_1_1memory__allocation__error.html", "classpni_1_1memory__allocation__error" ],
    [ "pni::memory_not_allocated_error", "classpni_1_1memory__not__allocated__error.html", "classpni_1_1memory__not__allocated__error" ],
    [ "pni::filter_not_available", "classpni_1_1filter__not__available.html", "classpni_1_1filter__not__available" ],
    [ "pni::shape_mismatch_error", "classpni_1_1shape__mismatch__error.html", "classpni_1_1shape__mismatch__error" ],
    [ "pni::size_mismatch_error", "classpni_1_1size__mismatch__error.html", "classpni_1_1size__mismatch__error" ],
    [ "pni::index_error", "classpni_1_1index__error.html", "classpni_1_1index__error" ],
    [ "pni::key_error", "classpni_1_1key__error.html", "classpni_1_1key__error" ],
    [ "pni::file_error", "classpni_1_1file__error.html", "classpni_1_1file__error" ],
    [ "pni::type_error", "classpni_1_1type__error.html", "classpni_1_1type__error" ],
    [ "pni::value_error", "classpni_1_1value__error.html", "classpni_1_1value__error" ],
    [ "pni::range_error", "classpni_1_1range__error.html", "classpni_1_1range__error" ],
    [ "pni::not_implemented_error", "classpni_1_1not__implemented__error.html", "classpni_1_1not__implemented__error" ],
    [ "pni::iterator_error", "classpni_1_1iterator__error.html", "classpni_1_1iterator__error" ],
    [ "pni::cli_argument_error", "classpni_1_1cli__argument__error.html", "classpni_1_1cli__argument__error" ],
    [ "pni::cli_option_error", "classpni_1_1cli__option__error.html", "classpni_1_1cli__option__error" ],
    [ "pni::cli_error", "classpni_1_1cli__error.html", "classpni_1_1cli__error" ],
    [ "pni::cli_help_request", "classpni_1_1cli__help__request.html", "classpni_1_1cli__help__request" ],
    [ "PNINEXUS_EXCEPTION_FORWARD", "error_2exceptions_8hpp.html#ab490a07665d904c3f915b44b6436cbfd", null ],
    [ "PNINEXUS_EXCEPTION_RECORD", "error_2exceptions_8hpp.html#af42ca9eab4d41a452a46ff61e10e7be5", null ],
    [ "operator<<", "error_2exceptions_8hpp.html#a66e44e53d5ab583ec3f8e0b94ad23991", null ]
];