var hierarchy =
[
    [ "pni::add_op< Operand1T, Operand2T >", "classpni_1_1add__op.html", null ],
    [ "pni::and_t< Operand1T, Operand2T >", "structpni_1_1and__t.html", null ],
    [ "pni::array", "classpni_1_1array.html", null ],
    [ "pni::array_factory< ArrayT >", "structpni_1_1array__factory.html", null ],
    [ "pni::array_holder_interface", "classpni_1_1array__holder__interface.html", [
      [ "pni::array_holder< ObjectT >", "classpni_1_1array__holder.html", null ]
    ] ],
    [ "pni::array_iterator< const_flag >", "classpni_1_1array__iterator.html", null ],
    [ "pni::array_iterator_types< const_flag >", "structpni_1_1array__iterator__types.html", null ],
    [ "pni::array_iterator_types< 0 >", "structpni_1_1array__iterator__types_3_010_01_4.html", null ],
    [ "pni::array_iterator_types< 1 >", "structpni_1_1array__iterator__types_3_011_01_4.html", null ],
    [ "pni::array_selection", "classpni_1_1array__selection.html", null ],
    [ "pni::array_trait< Operand1T, Operand2T >", "structpni_1_1array__trait.html", null ],
    [ "pni::array_trait< Operand1T, scalar< ScalarOperandT > >", "structpni_1_1array__trait_3_01Operand1T_00_01scalar_3_01ScalarOperandT_01_4_01_4.html", null ],
    [ "pni::array_trait< scalar< ScalarOperandT >, Operand1T >", "structpni_1_1array__trait_3_01scalar_3_01ScalarOperandT_01_4_00_01Operand1T_01_4.html", null ],
    [ "pni::array_view< ArrayT >", "classpni_1_1array__view.html", null ],
    [ "pni::array_view_trait< ArrayT, is_view >", "structpni_1_1array__view__trait.html", null ],
    [ "pni::array_view_trait< ArrayT, false >", "structpni_1_1array__view__trait_3_01ArrayT_00_01false_01_4.html", null ],
    [ "pni::array_view_trait< ArrayT, true >", "structpni_1_1array__view__trait_3_01ArrayT_00_01true_01_4.html", null ],
    [ "pni::nexus::BaseClassFactory", "classpni_1_1nexus_1_1BaseClassFactory.html", null ],
    [ "pni::binary_t< NativeT >", "classpni_1_1binary__t.html", null ],
    [ "pni::bool_t", "classpni_1_1bool__t.html", null ],
    [ "pni::nexus::xml::BuilderFactory", "classpni_1_1nexus_1_1xml_1_1BuilderFactory.html", null ],
    [ "pni::c_index_map_imp", "classpni_1_1c__index__map__imp.html", null ],
    [ "pni::checked_convertible< SourceT, TargetT >", "structpni_1_1checked__convertible.html", null ],
    [ "pni::column_info", "classpni_1_1column__info.html", null ],
    [ "pni::container_io_config", "classpni_1_1container__io__config.html", null ],
    [ "pni::container_iterator< IterableT >", "classpni_1_1container__iterator.html", null ],
    [ "pni::container_trait< ContainerT >", "structpni_1_1container__trait.html", null ],
    [ "pni::container_trait< array_view< ArrayT > >", "structpni_1_1container__trait_3_01array__view_3_01ArrayT_01_4_01_4.html", null ],
    [ "pni::container_trait< mdarray< StorageT, IndexMapT, InplaceArithmeticT > >", "structpni_1_1container__trait_3_01mdarray_3_01StorageT_00_01IndexMapT_00_01InplaceArithmeticT_01_4_01_4.html", null ],
    [ "pni::container_trait< std::array< DataT, TDimN > >", "structpni_1_1container__trait_3_01std_1_1array_3_01DataT_00_01TDimN_01_4_01_4.html", null ],
    [ "pni::container_trait< std::list< ArrayArgsT... > >", "structpni_1_1container__trait_3_01std_1_1list_3_01ArrayArgsT_8_8_8_01_4_01_4.html", null ],
    [ "pni::container_trait< std::vector< ArrayArgsT... > >", "structpni_1_1container__trait_3_01std_1_1vector_3_01ArrayArgsT_8_8_8_01_4_01_4.html", null ],
    [ "pni::container_utils< ContainerT >", "structpni_1_1container__utils.html", null ],
    [ "pni::container_utils< std::array< ElementT, TDimN > >", "structpni_1_1container__utils_3_01std_1_1array_3_01ElementT_00_01TDimN_01_4_01_4.html", null ],
    [ "pni::conversion_strategy< TargetT, SourceT, unchecked_convertible >", "structpni_1_1conversion__strategy.html", null ],
    [ "pni::conversion_strategy< hdf5::datatype::EBool, bool_t, true >", "structpni_1_1conversion__strategy_3_01hdf5_1_1datatype_1_1EBool_00_01bool__t_00_01true_01_4.html", null ],
    [ "pni::conversion_strategy< TargetT, SourceT, false >", "structpni_1_1conversion__strategy_3_01TargetT_00_01SourceT_00_01false_01_4.html", null ],
    [ "pni::conversion_trait< GeneralT >", "structpni_1_1conversion__trait.html", null ],
    [ "pni::conversion_trait< pni::int8 >", "structpni_1_1conversion__trait_3_01pni_1_1int8_01_4.html", null ],
    [ "pni::conversion_trait< pni::uint8 >", "structpni_1_1conversion__trait_3_01pni_1_1uint8_01_4.html", null ],
    [ "pni::converter< TargetT, SourceT >", "structpni_1_1converter.html", null ],
    [ "pni::converter< std::complex< BaseT >, SourceT >", "structpni_1_1converter_3_01std_1_1complex_3_01BaseT_01_4_00_01SourceT_01_4.html", null ],
    [ "pni::converter< std::complex< TargetBaseT >, std::complex< SourceBaseT > >", "structpni_1_1converter_3_01std_1_1complex_3_01TargetBaseT_01_4_00_01std_1_1complex_3_01SourceBaseT_01_4_01_4.html", null ],
    [ "pni::converter< TargetT, TargetT >", "structpni_1_1converter_3_01TargetT_00_01TargetT_01_4.html", null ],
    [ "pni::convertible< SourceT, TargetT >", "structpni_1_1convertible.html", null ],
    [ "pni::data_reader", "classpni_1_1data__reader.html", [
      [ "pni::image_reader", "classpni_1_1image__reader.html", [
        [ "pni::cbf_reader", "classpni_1_1cbf__reader.html", null ],
        [ "pni::tiff_reader", "classpni_1_1tiff__reader.html", null ]
      ] ],
      [ "pni::spreadsheet_reader", "classpni_1_1spreadsheet__reader.html", [
        [ "pni::fio_reader", "classpni_1_1fio__reader.html", null ]
      ] ]
    ] ],
    [ "pni::nexus::xml::DatasetCreationListBuilder", "classpni_1_1nexus_1_1xml_1_1DatasetCreationListBuilder.html", null ],
    [ "pni::nexus::xml::DataspaceBuilder", "classpni_1_1nexus_1_1xml_1_1DataspaceBuilder.html", null ],
    [ "pni::nexus::xml::DatatypeBuilder", "classpni_1_1nexus_1_1xml_1_1DatatypeBuilder.html", null ],
    [ "pni::nexus::DatatypeFactory", "classpni_1_1nexus_1_1DatatypeFactory.html", null ],
    [ "pni::nexus::xml::DataWriter", "classpni_1_1nexus_1_1xml_1_1DataWriter.html", null ],
    [ "pni::nexus::DateTime", "classpni_1_1nexus_1_1DateTime.html", null ],
    [ "pni::cbf::dectris_reader", "classpni_1_1cbf_1_1dectris__reader.html", null ],
    [ "pni::nexus::xml::DimensionNodeHandler", "classpni_1_1nexus_1_1xml_1_1DimensionNodeHandler.html", null ],
    [ "pni::div_op< Operand1T, Operand2T >", "classpni_1_1div__op.html", null ],
    [ "std::exception", null, [
      [ "pni::exception", "classpni_1_1exception.html", [
        [ "pni::cli_argument_error", "classpni_1_1cli__argument__error.html", null ],
        [ "pni::cli_error", "classpni_1_1cli__error.html", null ],
        [ "pni::cli_help_request", "classpni_1_1cli__help__request.html", null ],
        [ "pni::cli_option_error", "classpni_1_1cli__option__error.html", null ],
        [ "pni::file_error", "classpni_1_1file__error.html", null ],
        [ "pni::filter_not_available", "classpni_1_1filter__not__available.html", null ],
        [ "pni::index_error", "classpni_1_1index__error.html", null ],
        [ "pni::invalid_object_error", "classpni_1_1invalid__object__error.html", null ],
        [ "pni::io_error", "classpni_1_1io__error.html", null ],
        [ "pni::iterator_error", "classpni_1_1iterator__error.html", null ],
        [ "pni::key_error", "classpni_1_1key__error.html", null ],
        [ "pni::link_error", "classpni_1_1link__error.html", null ],
        [ "pni::memory_allocation_error", "classpni_1_1memory__allocation__error.html", null ],
        [ "pni::memory_not_allocated_error", "classpni_1_1memory__not__allocated__error.html", null ],
        [ "pni::not_implemented_error", "classpni_1_1not__implemented__error.html", null ],
        [ "pni::object_error", "classpni_1_1object__error.html", null ],
        [ "pni::parser_error", "classpni_1_1parser__error.html", null ],
        [ "pni::range_error", "classpni_1_1range__error.html", null ],
        [ "pni::shape_mismatch_error", "classpni_1_1shape__mismatch__error.html", null ],
        [ "pni::size_mismatch_error", "classpni_1_1size__mismatch__error.html", null ],
        [ "pni::tiff::tiff_read_error", "classpni_1_1tiff_1_1tiff__read__error.html", null ],
        [ "pni::type_error", "classpni_1_1type__error.html", null ],
        [ "pni::value_error", "classpni_1_1value__error.html", null ]
      ] ]
    ] ],
    [ "pni::exception_record", "classpni_1_1exception__record.html", null ],
    [ "pni::nexus::FieldFactory", "classpni_1_1nexus_1_1FieldFactory.html", null ],
    [ "pni::format_config", "classpni_1_1format__config.html", null ],
    [ "pni::format_str< ElementT >", "structpni_1_1format__str.html", null ],
    [ "pni::get_reference_type< GeneralT >", "structpni_1_1get__reference__type.html", null ],
    [ "pni::get_reference_type< std::reference_wrapper< GeneralT > >", "structpni_1_1get__reference__type_3_01std_1_1reference__wrapper_3_01GeneralT_01_4_01_4.html", null ],
    [ "pni::id_type_map< id >", "structpni_1_1id__type__map.html", null ],
    [ "pni::tiff::ifd", "classpni_1_1tiff_1_1ifd.html", null ],
    [ "pni::tiff::ifd_entry", "classpni_1_1tiff_1_1ifd__entry.html", null ],
    [ "pni::tiff::ifd_entry_reader< ReadT, EntryDataT >", "classpni_1_1tiff_1_1ifd__entry__reader.html", null ],
    [ "pni::tiff::ifd_entry_reader< pni::string, pni::string >", "classpni_1_1tiff_1_1ifd__entry__reader_3_01pni_1_1string_00_01pni_1_1string_01_4.html", null ],
    [ "pni::image_channel_info", "classpni_1_1image__channel__info.html", null ],
    [ "pni::image_info", "classpni_1_1image__info.html", null ],
    [ "pni::index_iterator< IndexT, IndexMapT >", "classpni_1_1index__iterator.html", null ],
    [ "pni::index_map< ShapeStoreT, MapImpT >", "classpni_1_1index__map.html", null ],
    [ "pni::index_map< index_type, typename ArrayT::map_type::implementation_type >", "classpni_1_1index__map.html", null ],
    [ "pni::inplace_arithmetics", "structpni_1_1inplace__arithmetics.html", null ],
    [ "pni::is_array< GeneralT >", "structpni_1_1is__array.html", null ],
    [ "pni::is_complex_type< GeneralT >", "structpni_1_1is__complex__type.html", null ],
    [ "pni::is_float_type< GeneralT >", "structpni_1_1is__float__type.html", null ],
    [ "pni::is_index_type< GeneralT >", "structpni_1_1is__index__type.html", null ],
    [ "pni::is_index_types< IndicesT >::is_index_type_pred< InputT >", "structpni_1_1is__index__types_1_1is__index__type__pred.html", null ],
    [ "pni::is_index_types< IndicesT >", "structpni_1_1is__index__types.html", null ],
    [ "pni::is_integer_type< GeneralT >", "structpni_1_1is__integer__type.html", null ],
    [ "pni::is_non_numeric_type< GeneralT >", "structpni_1_1is__non__numeric__type.html", null ],
    [ "pni::is_numeric_type< GeneralT >", "structpni_1_1is__numeric__type.html", null ],
    [ "pni::is_primitive_type< GeneralT >", "structpni_1_1is__primitive__type.html", null ],
    [ "pni::is_reference_holder< GeneralT >", "structpni_1_1is__reference__holder.html", null ],
    [ "pni::is_reference_holder< std::reference_wrapper< GeneralT > >", "structpni_1_1is__reference__holder_3_01std_1_1reference__wrapper_3_01GeneralT_01_4_01_4.html", null ],
    [ "pni::is_valid_index< IndicesT >", "structpni_1_1is__valid__index.html", null ],
    [ "pni::is_view_cont< ContainerT >", "structpni_1_1is__view__cont.html", null ],
    [ "pni::is_view_cont< std::array< ElementT, TDimN > >", "structpni_1_1is__view__cont_3_01std_1_1array_3_01ElementT_00_01TDimN_01_4_01_4.html", null ],
    [ "pni::is_view_cont< std::vector< ElementT > >", "structpni_1_1is__view__cont_3_01std_1_1vector_3_01ElementT_01_4_01_4.html", null ],
    [ "pni::is_view_index< IndicesT >", "structpni_1_1is__view__index.html", null ],
    [ "pni::nexus::IsValidNeXusName", "classpni_1_1nexus_1_1IsValidNeXusName.html", null ],
    [ "pni::nx::xml::link", "classpni_1_1nx_1_1xml_1_1link.html", null ],
    [ "std::list< T >", null, [
      [ "pni::nexus::PathObjectList", "classpni_1_1nexus_1_1PathObjectList.html", null ]
    ] ],
    [ "pni::map_utils< MapT >", "structpni_1_1map__utils.html", null ],
    [ "pni::map_utils< static_index_map< PolicyT, TDimsN... > >", "structpni_1_1map__utils_3_01static__index__map_3_01PolicyT_00_01TDimsN_8_8_8_01_4_01_4.html", null ],
    [ "pni::mdarray< StorageT, IndexMapT, InplaceArithmeticT >", "classpni_1_1mdarray.html", null ],
    [ "pni::min_max< IntegerT, is_float >", "structpni_1_1min__max.html", null ],
    [ "pni::min_max< FloatT, true >", "structpni_1_1min__max_3_01FloatT_00_01true_01_4.html", null ],
    [ "pni::mult_op< Operand1T, Operand2T >", "classpni_1_1mult__op.html", null ],
    [ "pni::nexus::NodePredicate", "classpni_1_1nexus_1_1NodePredicate.html", [
      [ "pni::nexus::IsBaseClass", "classpni_1_1nexus_1_1IsBaseClass.html", [
        [ "pni::nexus::IsData", "classpni_1_1nexus_1_1IsData.html", null ],
        [ "pni::nexus::IsDetector", "classpni_1_1nexus_1_1IsDetector.html", null ],
        [ "pni::nexus::IsEntry", "classpni_1_1nexus_1_1IsEntry.html", null ],
        [ "pni::nexus::IsInstrument", "classpni_1_1nexus_1_1IsInstrument.html", null ],
        [ "pni::nexus::IsSample", "classpni_1_1nexus_1_1IsSample.html", null ],
        [ "pni::nexus::IsSubentry", "classpni_1_1nexus_1_1IsSubentry.html", null ],
        [ "pni::nexus::IsTransformation", "classpni_1_1nexus_1_1IsTransformation.html", null ]
      ] ]
    ] ],
    [ "pni::none", "structpni_1_1none.html", null ],
    [ "pni::not_t< FunctionT >", "structpni_1_1not__t.html", null ],
    [ "pni::nexus::ObjectBuilder", "classpni_1_1nexus_1_1ObjectBuilder.html", [
      [ "pni::nexus::xml::ObjectBuilder", "classpni_1_1nexus_1_1xml_1_1ObjectBuilder.html", [
        [ "pni::nexus::xml::AttributeBuilder", "classpni_1_1nexus_1_1xml_1_1AttributeBuilder.html", null ],
        [ "pni::nexus::xml::FieldBuilder", "classpni_1_1nexus_1_1xml_1_1FieldBuilder.html", null ],
        [ "pni::nexus::xml::GroupBuilder", "classpni_1_1nexus_1_1xml_1_1GroupBuilder.html", null ],
        [ "pni::nexus::xml::LinkBuilder", "classpni_1_1nexus_1_1xml_1_1LinkBuilder.html", null ]
      ] ]
    ] ],
    [ "pni::op_trait< OperatorT >", "structpni_1_1op__trait.html", null ],
    [ "pni::op_trait< Operand1T >", "structpni_1_1op__trait.html", null ],
    [ "pni::op_trait< Operand2T >", "structpni_1_1op__trait.html", null ],
    [ "pni::op_trait< scalar< GeneralT > >", "structpni_1_1op__trait_3_01scalar_3_01GeneralT_01_4_01_4.html", null ],
    [ "pni::or_t< Operand1T, Operand2T >", "structpni_1_1or__t.html", null ],
    [ "pni::parser< T >", "classpni_1_1parser.html", null ],
    [ "pni::parser< base_type >", "classpni_1_1parser.html", null ],
    [ "pni::parser< hdf5::datatype::EBool >", "classpni_1_1parser_3_01hdf5_1_1datatype_1_1EBool_01_4.html", null ],
    [ "pni::parser< pni::bool_t >", "classpni_1_1parser_3_01pni_1_1bool__t_01_4.html", null ],
    [ "pni::parser< pni::complex64 >", "classpni_1_1parser.html", null ],
    [ "pni::parser< pni::float64 >", "classpni_1_1parser.html", null ],
    [ "pni::parser< pni::int64 >", "classpni_1_1parser.html", null ],
    [ "pni::parser< pni::slice >", "classpni_1_1parser_3_01pni_1_1slice_01_4.html", null ],
    [ "pni::parser< pni::string >", "classpni_1_1parser_3_01pni_1_1string_01_4.html", null ],
    [ "pni::parser< pni::value >", "classpni_1_1parser_3_01pni_1_1value_01_4.html", null ],
    [ "pni::parser< std::complex< BaseT > >", "classpni_1_1parser_3_01std_1_1complex_3_01BaseT_01_4_01_4.html", null ],
    [ "pni::parser< std::vector< ElementT > >", "classpni_1_1parser_3_01std_1_1vector_3_01ElementT_01_4_01_4.html", null ],
    [ "pni::parser< value_type >", "classpni_1_1parser.html", null ],
    [ "pni::nexus::Path", "classpni_1_1nexus_1_1Path.html", null ],
    [ "pni::nexus::PathObject", "classpni_1_1nexus_1_1PathObject.html", null ],
    [ "boost::property_tree::ptree", null, [
      [ "pni::nexus::xml::Node", "classpni_1_1nexus_1_1xml_1_1Node.html", null ]
    ] ],
    [ "pni::tiff::rational< IntegerT >", "classpni_1_1tiff_1_1rational.html", null ],
    [ "pni::scalar< ElementT >", "classpni_1_1scalar.html", null ],
    [ "pni::scalar_iterator< IterableT >", "classpni_1_1scalar__iterator.html", null ],
    [ "pni::slice", "classpni_1_1slice.html", null ],
    [ "pni::static_index_map< MapImpT, TDimsN >", "classpni_1_1static__index__map.html", null ],
    [ "pni::tiff::strip_reader", "classpni_1_1tiff_1_1strip__reader.html", null ],
    [ "pni::sub_op< Operand1T, Operand2T >", "classpni_1_1sub__op.html", null ],
    [ "pni::type_class_map< ElementT >", "structpni_1_1type__class__map.html", null ],
    [ "pni::type_id_container_builder< ContainerT >", "classpni_1_1type__id__container__builder.html", null ],
    [ "pni::type_id_map< ElementT >", "structpni_1_1type__id__map.html", null ],
    [ "pni::type_info< GeneralT >", "structpni_1_1type__info.html", null ],
    [ "hdf5::dataspace::TypeTrait< pni::array >", "classhdf5_1_1dataspace_1_1TypeTrait_3_01pni_1_1array_01_4.html", null ],
    [ "hdf5::datatype::TypeTrait< pni::array >", "classhdf5_1_1datatype_1_1TypeTrait_3_01pni_1_1array_01_4.html", null ],
    [ "hdf5::dataspace::TypeTrait< pni::mdarray< StorageT, IndexMapT, InplaceArithmeticT > >", "classhdf5_1_1dataspace_1_1TypeTrait_3_01pni_1_1mdarray_3_01StorageT_00_01IndexMapT_00_01InplaceArithmeticT_01_4_01_4.html", null ],
    [ "hdf5::datatype::TypeTrait< pni::mdarray< StorageT, IndexMapT, InplaceArithmeticT > >", "classhdf5_1_1datatype_1_1TypeTrait_3_01pni_1_1mdarray_3_01StorageT_00_01IndexMapT_00_01InplaceArithmeticT_01_4_01_4.html", null ],
    [ "pni::unchecked_convertible< SourceT, TargetT >", "structpni_1_1unchecked__convertible.html", null ],
    [ "pni::value", "classpni_1_1value.html", null ],
    [ "pni::value_converter< TargetT, SourceT, convertible >", "structpni_1_1value__converter.html", null ],
    [ "pni::value_converter< TargetT, SourceT, true >", "structpni_1_1value__converter_3_01TargetT_00_01SourceT_00_01true_01_4.html", null ],
    [ "pni::value_holder_interface", "classpni_1_1value__holder__interface.html", [
      [ "pni::value_holder< GeneralT >", "classpni_1_1value__holder.html", null ]
    ] ],
    [ "pni::value_ref", "classpni_1_1value__ref.html", null ],
    [ "hdf5::VarLengthStringTrait< pni::dynamic_array< std::string > >", "classhdf5_1_1VarLengthStringTrait_3_01pni_1_1dynamic__array_3_01std_1_1string_01_4_01_4.html", null ],
    [ "std::vector< T >", null, [
      [ "pni::nexus::AttributeList", "classpni_1_1nexus_1_1AttributeList.html", null ],
      [ "pni::nexus::DatasetList", "classpni_1_1nexus_1_1DatasetList.html", null ],
      [ "pni::nexus::GroupList", "classpni_1_1nexus_1_1GroupList.html", null ],
      [ "pni::nexus::NodeList", "classpni_1_1nexus_1_1NodeList.html", null ]
    ] ],
    [ "pni::nexus::Version", "classpni_1_1nexus_1_1Version.html", null ],
    [ "pni::view_provider< RightT, is_view >", "structpni_1_1view__provider.html", null ],
    [ "pni::view_provider< ArrayT, false >", "structpni_1_1view__provider_3_01ArrayT_00_01false_01_4.html", null ],
    [ "pni::view_provider< ArrayT, true >", "structpni_1_1view__provider_3_01ArrayT_00_01true_01_4.html", null ]
];